# By default, SwiftLint uses a set of sensible default rules you can adjust:
disabled_rules: # rule identifiers turned on by default to exclude from running

  - multiple_closures_with_trailing_closure

opt_in_rules: # some rules are turned off by default, so you need to opt-in
  - contains_over_first_not_nil
  - empty_count
  - first_where
  - force_unwrapping
  - implicit_return
  - missing_docs
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_whitespace
  - prohibited_interface_builder
  - unneeded_parentheses_in_closure_argument
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - docs
  - .build

# configurable rules can be customized from this configuration file
# binary rules can set their severity level

cyclomatic_complexity:
  ignores_case_statements: true
  
identifier_name:
  min_length: 1

trailing_whitespace:
  ignores_empty_lines: true

function_parameter_count:
  warning: 6
