package co.yml.ychat.domain.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Represents a image generated by a prompt, consisting of a [url] generated by the system (AI).
 * @property url The url of the image generated by the input provided.
 */
@Serializable
data class ImageGenerated(
    @SerialName("url")
    val url: String,
)
