name: Main CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  code-check:
    name: Code Check
    runs-on: ubuntu-latest
    steps:
      ## Step 1
      - name: Checkout
        uses: actions/checkout@v3
      ## Step 2
      - name: Run Clean
        run: ./gradlew clean
      ## Step 3
      - name: Check Swift Package Version
        run: ./gradlew checkSwiftPackageVersion
      ## Step 4
      - name: Run Detekt
        run: ./gradlew :chat-gpt:detektMetadataMain
      ## Step 5
      - name: Run Ktlint
        run: ./gradlew :chat-gpt:ktlintCheck

  code-coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      ## Step 1
      - name: Checkout
        uses: actions/checkout@v3
      ## Step 2
      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      ## Step 3
      - name: Run Kover Verify
        run: ./gradlew koverVerify
      ## Step 4
      - name: Upload Test Report
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: Test Report
          path: "**/build/reports/tests/testDebugUnitTest"
      ## Step 5
      - name: Run Kover Report
        run: ./gradlew :chat-gpt:koverXmlReport
      ## Step 6
      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          files: "**/build/reports/kover/xml/report.xml"